/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.user;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import bioskop.dao.OrderDAO;
import bioskop.model.Order;
import bioskop.model.OrderFoodDetail;
import bioskop.model.OrderPackageDetail;
import bioskop.model.OrderTicketDetail;
import bioskop.view.auth.LoginFrame;

/**
 *
 * @author aryab
 */
public class TransactionHistoryFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionHistoryFrame.class.getName());
    
    private int idUserSesi = 1;
    /**
     * Creates new form TransactionHistoryFrame
     */
    public TransactionHistoryFrame() {
        initComponents();
        loadRiwayatTabel();
    }
    
    private void loadRiwayatTabel() {
        DefaultTableModel model = (DefaultTableModel) RiwayatTable.getModel();
        model.setRowCount(0); // Kosongkan tabel sebelum diisi

        OrderDAO dao = new OrderDAO();
        List<Order> listOrder = dao.getRiwayatOrderByUser(idUserSesi);

        // Urutan Kolom: ID Pesanan, Tanggal Transaksi, Total Bayar, Status
        for (Order o : listOrder) {
            model.addRow(new Object[]{
                o.getIdOrder(),
                o.getTanggalOrder(),
                o.getTotalHarga(),
                o.getStatusPembayaran()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RiwayatTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        DetailTable = new javax.swing.JTable();
        MenuUtamaButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Riwayat Transaksi");

        RiwayatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pemesanan", "Tanggal Transaksi", "Total Harga", "Status"
            }
        ));
        RiwayatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RiwayatTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RiwayatTable);

        DetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipe Item", "Nama / No Kursi", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane4.setViewportView(DetailTable);

        MenuUtamaButton.setText("Menu Utama");
        MenuUtamaButton.addActionListener(this::MenuUtamaButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MenuUtamaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LogoutButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MenuUtamaButton)
                            .addComponent(LogoutButton))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RiwayatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RiwayatTableMouseClicked
        // TODO add your handling code here:
        int barisTerpilih = RiwayatTable.getSelectedRow();
        
        if (barisTerpilih != -1) {
            // Ambil ID Order dari kolom pertama (index 0) yang diklik
            int idOrder = Integer.parseInt(RiwayatTable.getValueAt(barisTerpilih, 0).toString());
            
            DefaultTableModel modelDetail = (DefaultTableModel) DetailTable.getModel();
            modelDetail.setRowCount(0); // Kosongkan tabel detail

            OrderDAO dao = new OrderDAO();

            // 1. Tampilkan Rincian Tiket
            List<OrderTicketDetail> listTiket = dao.getDetailTicketByOrder(idOrder);
            for (OrderTicketDetail t : listTiket) {
                modelDetail.addRow(new Object[]{
                    "Tiket Bioskop",
                    "Kursi " + t.getNomorKursi(),
                    1, // Tiket selalu dihitung 1 per baris/kursi
                    t.getHarga()
                });
            }

            // 2. Tampilkan Rincian Makanan Satuan
            List<OrderFoodDetail> listFood = dao.getDetailFoodByOrder(idOrder);
            for (OrderFoodDetail f : listFood) {
                modelDetail.addRow(new Object[]{
                    "Makanan/Minuman",
                    f.getNamaFood(),
                    f.getJumlah(),
                    f.getSubtotal()
                });
            }

            // 3. Tampilkan Rincian Paket Makanan
            List<OrderPackageDetail> listPackage = dao.getDetailPackageByOrder(idOrder);
            for (OrderPackageDetail p : listPackage) {
                modelDetail.addRow(new Object[]{
                    "Paket Makanan",
                    p.getNamaPaket(),
                    p.getJumlah(),
                    p.getSubtotal()
                });
            }
        }
    }//GEN-LAST:event_RiwayatTableMouseClicked

    private void MenuUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtamaButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenuFrame().setVisible(true);
    }//GEN-LAST:event_MenuUtamaButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionHistoryFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DetailTable;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MenuUtamaButton;
    private javax.swing.JTable RiwayatTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
