/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.admin;

import bioskop.view.auth.LoginFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import bioskop.dao.FilmDAO;
import bioskop.model.Film;

public class FilmFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FilmFrame.class.getName());
    private int idFilmTerpilih = -1;

    public FilmFrame() {
        initComponents();
        loadDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        judulTextField = new javax.swing.JTextField();
        genreTextField = new javax.swing.JTextField();
        durasiTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinopsisTextArea = new javax.swing.JTextArea();
        status_tayangComboBox = new javax.swing.JComboBox<>();
        tambahButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        filmTable = new javax.swing.JTable();
        LogoutButton = new javax.swing.JButton();
        MenuUtamaButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kelola FIlm");

        jLabel2.setText("Judul");

        jLabel3.setText("Genre");

        jLabel4.setText("Durasi (menit)");

        jLabel5.setText("Sinopsis");

        jLabel6.setText("Status");

        genreTextField.addActionListener(this::genreTextFieldActionPerformed);

        sinopsisTextArea.setColumns(20);
        sinopsisTextArea.setRows(5);
        jScrollPane1.setViewportView(sinopsisTextArea);

        status_tayangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Now Playing", "Coming Soon", "Not Showing" }));
        status_tayangComboBox.setSelectedIndex(-1);

        tambahButton.setText("Tambah");
        tambahButton.addActionListener(this::tambahButtonActionPerformed);

        editButton.setText("Edit");
        editButton.addActionListener(this::editButtonActionPerformed);

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(this::hapusButtonActionPerformed);

        filmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul", "Genre", "Durasi", "Sinopsis", "Status"
            }
        ));
        filmTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(filmTable);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        MenuUtamaButton.setText("Menu Utama");
        MenuUtamaButton.addActionListener(this::MenuUtamaButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6)
                            .addComponent(tambahButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton)
                                .addGap(83, 83, 83)
                                .addComponent(hapusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MenuUtamaButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(durasiTextField)
                                    .addComponent(genreTextField)
                                    .addComponent(judulTextField)
                                    .addComponent(status_tayangComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(278, 278, 278))))
                    .addComponent(LogoutButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(266, 266, 266)
                            .addComponent(jLabel1))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durasiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(status_tayangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuUtamaButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tambahButton)
                        .addComponent(editButton)
                        .addComponent(hapusButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadDataTable(){
        // Ambil model dari filmTabel dan kosongkan data lama
        DefaultTableModel model = (DefaultTableModel) filmTable.getModel();
        model.setRowCount(0);

        FilmDAO filmDAO = new FilmDAO();
        List<Film> listFilm = filmDAO.getAllFilms();

    // Pastikan susunan kolom di JTable kamu: ID, Judul, Genre, Durasi, Sinopsis, Status
        for (Film f : listFilm) {
            model.addRow(new Object[]{
                f.getIdFilm(),
                f.getJudulFilm(),
                f.getGenre(),
                f.getDurasi(),
                f.getSinopsis(),
                f.getStatusTayang()
            });
        }
    }
    
    private void clearFields() {
        judulTextField.setText("");
        genreTextField.setText("");
        durasiTextField.setText("");
        sinopsisTextArea.setText("");
        status_tayangComboBox.setSelectedIndex(0);
        idFilmTerpilih = -1; // Reset ID tersembunyi
    }
    
    private void genreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreTextFieldActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        String judul = judulTextField.getText();
        String genre = genreTextField.getText();
        String durasiStr = durasiTextField.getText();
        String sinopsis = sinopsisTextArea.getText();
        String status = status_tayangComboBox.getSelectedItem().toString();

        // Validasi Input Kosong
        if (judul.isEmpty() || genre.isEmpty() || durasiStr.isEmpty() || sinopsis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua formulir harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int durasi = Integer.parseInt(durasiStr);
            Film film = new Film(0, judul, genre, durasi, sinopsis, status);
            FilmDAO filmDAO = new FilmDAO();

            if (filmDAO.insertFilm(film)) {
                JOptionPane.showMessageDialog(this, "Film baru berhasil ditambahkan!");
                loadDataTable(); // Refresh tabel
                clearFields();   // Kosongkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan film.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Durasi harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (idFilmTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data film dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String judul = judulTextField.getText();
        String genre = genreTextField.getText();
        String durasiStr = durasiTextField.getText();
        String sinopsis = sinopsisTextArea.getText();
        String status = status_tayangComboBox.getSelectedItem().toString();

        if (judul.isEmpty() || genre.isEmpty() || durasiStr.isEmpty() || sinopsis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua formulir harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int durasi = Integer.parseInt(durasiStr);
            Film film = new Film(idFilmTerpilih, judul, genre, durasi, sinopsis, status);
            FilmDAO filmDAO = new FilmDAO();

            if (filmDAO.updateFilm(film)) {
                JOptionPane.showMessageDialog(this, "Data film berhasil diperbarui!");
                loadDataTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data film.");
            }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Durasi harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void filmTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmTableMouseClicked
        // TODO add your handling code here:
        int row = filmTable.getSelectedRow();
        if (row != -1) {
        // Mengambil data dari kolom tabel (Urutan kolom sesuai index 0-5)
            idFilmTerpilih = Integer.parseInt(filmTable.getValueAt(row, 0).toString());
            judulTextField.setText(filmTable.getValueAt(row, 1).toString());
            genreTextField.setText(filmTable.getValueAt(row, 2).toString());
            durasiTextField.setText(filmTable.getValueAt(row, 3).toString());
            sinopsisTextArea.setText(filmTable.getValueAt(row, 4).toString());
            status_tayangComboBox.setSelectedItem(filmTable.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_filmTableMouseClicked

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        if (idFilmTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data film dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus film ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            FilmDAO filmDAO = new FilmDAO();
            if (filmDAO.deleteFilm(idFilmTerpilih)) {
                JOptionPane.showMessageDialog(this, "Film berhasil dihapus!");
                loadDataTable();
                clearFields();
            } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus film.");
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void MenuUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtamaButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuAdminFrame().setVisible(true);
    }//GEN-LAST:event_MenuUtamaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FilmFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MenuUtamaButton;
    private javax.swing.JTextField durasiTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JTable filmTable;
    private javax.swing.JTextField genreTextField;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judulTextField;
    private javax.swing.JTextArea sinopsisTextArea;
    private javax.swing.JComboBox<String> status_tayangComboBox;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}
