/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.admin;

import bioskop.view.auth.LoginFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aryab
 */
public class MenuAdminFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdminFrame.class.getName());

    /**
     * Creates new form MenuAdminFrame
     */
    public MenuAdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        KelolaFilmButton = new javax.swing.JButton();
        KelolaJadwalTayangButton = new javax.swing.JButton();
        KelolaStudioButton = new javax.swing.JButton();
        KelolaKursiButton = new javax.swing.JButton();
        KelolaDataTransaksiButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        KelolaMakananMinumanButton = new javax.swing.JButton();
        KelolaPaketComboButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Menu Utama");

        KelolaFilmButton.setText("Film");
        KelolaFilmButton.addActionListener(this::KelolaFilmButtonActionPerformed);

        KelolaJadwalTayangButton.setText("Jadwal Tayang");
        KelolaJadwalTayangButton.addActionListener(this::KelolaJadwalTayangButtonActionPerformed);

        KelolaStudioButton.setText("Studio");
        KelolaStudioButton.addActionListener(this::KelolaStudioButtonActionPerformed);

        KelolaKursiButton.setText("Kursi");
        KelolaKursiButton.addActionListener(this::KelolaKursiButtonActionPerformed);

        KelolaDataTransaksiButton.setText("Data Transaksi");
        KelolaDataTransaksiButton.addActionListener(this::KelolaDataTransaksiButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        KelolaMakananMinumanButton.setText("Makanan & Minuman");
        KelolaMakananMinumanButton.addActionListener(this::KelolaMakananMinumanButtonActionPerformed);

        KelolaPaketComboButton.setText("Paket Combo");
        KelolaPaketComboButton.addActionListener(this::KelolaPaketComboButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KelolaKursiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KelolaStudioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KelolaFilmButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(KelolaJadwalTayangButton))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KelolaDataTransaksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(KelolaPaketComboButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(LogoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(KelolaMakananMinumanButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelolaFilmButton)
                    .addComponent(KelolaJadwalTayangButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KelolaDataTransaksiButton)
                    .addComponent(KelolaStudioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KelolaKursiButton)
                    .addComponent(KelolaPaketComboButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KelolaMakananMinumanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KelolaJadwalTayangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaJadwalTayangButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ShowtimeFrame().setVisible(true);
    }//GEN-LAST:event_KelolaJadwalTayangButtonActionPerformed

    private void KelolaKursiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaKursiButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SeatFrame().setVisible(true);
    }//GEN-LAST:event_KelolaKursiButtonActionPerformed

    private void KelolaDataTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaDataTransaksiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelolaDataTransaksiButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void KelolaFilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaFilmButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FilmFrame().setVisible(true);
    }//GEN-LAST:event_KelolaFilmButtonActionPerformed

    private void KelolaStudioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaStudioButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StudioFrame().setVisible(true);
    }//GEN-LAST:event_KelolaStudioButtonActionPerformed

    private void KelolaMakananMinumanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaMakananMinumanButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FoodFrame().setVisible(true);
    }//GEN-LAST:event_KelolaMakananMinumanButtonActionPerformed

    private void KelolaPaketComboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaPaketComboButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PackageFoodFrame().setVisible(true);
    }//GEN-LAST:event_KelolaPaketComboButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdminFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KelolaDataTransaksiButton;
    private javax.swing.JButton KelolaFilmButton;
    private javax.swing.JButton KelolaJadwalTayangButton;
    private javax.swing.JButton KelolaKursiButton;
    private javax.swing.JButton KelolaMakananMinumanButton;
    private javax.swing.JButton KelolaPaketComboButton;
    private javax.swing.JButton KelolaStudioButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
