/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.admin;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import bioskop.view.auth.LoginFrame;
import bioskop.dao.FoodDAO;
import bioskop.dao.FoodPackageDAO;
import bioskop.model.Food;
import bioskop.model.FoodPackage;
import bioskop.model.FoodPackageDetail;

public class PackageFoodFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PackageFoodFrame.class.getName());
    
    private List<FoodPackageDetail> keranjang = new ArrayList<>();
    private int indexKeranjangTerpilih = -1;
    
    public PackageFoodFrame() {
        initComponents();
        loadComboBoxData();
        refreshKeranjangTabel();
    }
    
    private void loadComboBoxData() {
        MakananComboBox.removeAllItems();
        FoodDAO foodDAO = new FoodDAO();
        for (Food f : foodDAO.getAllFoods()) {
            MakananComboBox.addItem(f); // Memasukkan objek Food utuh
        }
    }

    private void refreshKeranjangTabel() {
        DefaultTableModel model = (DefaultTableModel) KeranjangTable.getModel();
        model.setRowCount(0); // Bersihkan tampilan tabel

        // Menampilkan ulang isi list keranjang ke tabel
        // Urutan Kolom: Nama Makanan (0), Jumlah (1)
        for (FoodPackageDetail detail : keranjang) {
            model.addRow(new Object[]{
                detail.getNamaFood(),
                detail.getJumlah()
            });
        }
        indexKeranjangTerpilih = -1; // Reset baris terpilih
    }

    private void clearSemuaForm() {
        NamaPaketTextField.setText("");
        HargaTextField.setText("");
        DeskripsiTextArea.setText("");
        if(MakananComboBox.getItemCount() > 0) MakananComboBox.setSelectedIndex(0);
        JumlahSpinner.setValue(0);
        keranjang.clear(); // Kosongkan keranjang di memori
        refreshKeranjangTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NamaPaketTextField = new javax.swing.JTextField();
        HargaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeskripsiTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        MakananComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        JumlahSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        KeranjangTable = new javax.swing.JTable();
        TambahPaketButton = new javax.swing.JButton();
        SimpanPaketButton = new javax.swing.JButton();
        EditPaketButton = new javax.swing.JButton();
        HapusPaketButton = new javax.swing.JButton();
        MenuUtamaButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kelola Paket Makanan & Minuman");

        jLabel2.setText("Nama");

        jLabel3.setText("Harga");

        jLabel4.setText("Deskripsi");

        NamaPaketTextField.addActionListener(this::NamaPaketTextFieldActionPerformed);

        DeskripsiTextArea.setColumns(20);
        DeskripsiTextArea.setRows(5);
        jScrollPane1.setViewportView(DeskripsiTextArea);

        jLabel5.setText("Makanan");

        MakananComboBox.setSelectedIndex(-1);

        jLabel6.setText("Jumlah");

        KeranjangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Makanan", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KeranjangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeranjangTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(KeranjangTable);

        TambahPaketButton.setText("Tambahkan ke tabel Paket");
        TambahPaketButton.addActionListener(this::TambahPaketButtonActionPerformed);

        SimpanPaketButton.setText("Simpan Paket");
        SimpanPaketButton.addActionListener(this::SimpanPaketButtonActionPerformed);

        EditPaketButton.setText("Edit data Paket");
        EditPaketButton.addActionListener(this::EditPaketButtonActionPerformed);

        HapusPaketButton.setText("Hapus data Paket");
        HapusPaketButton.addActionListener(this::HapusPaketButtonActionPerformed);

        MenuUtamaButton.setText("Menu Utama");
        MenuUtamaButton.addActionListener(this::MenuUtamaButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(HargaTextField)
                                        .addComponent(NamaPaketTextField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MakananComboBox, 0, 232, Short.MAX_VALUE)
                                        .addComponent(JumlahSpinner))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TambahPaketButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HapusPaketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditPaketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SimpanPaketButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MenuUtamaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LogoutButton)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NamaPaketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MakananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JumlahSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TambahPaketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditPaketButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HapusPaketButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SimpanPaketButton)
                            .addComponent(MenuUtamaButton)
                            .addComponent(LogoutButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaPaketTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPaketTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPaketTextFieldActionPerformed

    private void SimpanPaketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPaketButtonActionPerformed
        // TODO add your handling code here:
        String namaPaket = NamaPaketTextField.getText();
        String deskripsi = DeskripsiTextArea.getText();
        String hargaStr = HargaTextField.getText();

        // Validasi
        if (namaPaket.isEmpty() || hargaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Paket dan Harga Utama harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (keranjang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang paket tidak boleh kosong! Tambahkan minimal 1 makanan/minuman.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double hargaPaket = Double.parseDouble(hargaStr);
            
            // 1. Buat Objek Header Paket
            FoodPackage paketBaru = new FoodPackage(0, namaPaket, deskripsi, hargaPaket);
            
            // 2. Tempelkan isi keranjang kita ke dalam paket tersebut
            paketBaru.setDetails(keranjang);

            // 3. Kirimkan ke DAO untuk diproses SQL-nya
            FoodPackageDAO dao = new FoodPackageDAO();
            if (dao.insertFoodPackage(paketBaru)) {
                JOptionPane.showMessageDialog(this, "Paket Makanan berhasil disimpan ke Database secara permanen!");
                clearSemuaForm(); // Kosongkan semuanya agar siap input paket baru
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan paket ke Database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kolom harga harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SimpanPaketButtonActionPerformed

    private void KeranjangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeranjangTableMouseClicked
        // TODO add your handling code here:
        indexKeranjangTerpilih = KeranjangTable.getSelectedRow();
        if (indexKeranjangTerpilih != -1) {
            FoodPackageDetail detail = keranjang.get(indexKeranjangTerpilih);
            
            // Set MakananComboBox
            for (int i = 0; i < MakananComboBox.getItemCount(); i++) {
                if (MakananComboBox.getItemAt(i).toString().equals(detail.getNamaFood())) {
                    MakananComboBox.setSelectedIndex(i);
                    break;
                }
            }
            
            // Set Spinner Jumlah
            JumlahSpinner.setValue(detail.getJumlah());
        }
    }//GEN-LAST:event_KeranjangTableMouseClicked

    private void TambahPaketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPaketButtonActionPerformed
        // TODO add your handling code here:
        Food selectedFood = (Food) MakananComboBox.getSelectedItem();
        int jumlah = Integer.parseInt(JumlahSpinner.getValue().toString());

        if (selectedFood == null || jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Pilih makanan dan pastikan jumlah lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Membuat objek detail sementara (ID Paket dan ID Detail diset 0 dulu karena belum masuk database)
        FoodPackageDetail detailBaru = new FoodPackageDetail(0, 0, selectedFood.getIdFood(), jumlah);
        detailBaru.setNamaFood(selectedFood.getNamaFood()); // Set nama untuk ditampilkan di tabel
        
        keranjang.add(detailBaru); // Masukkan ke memori RAM
        refreshKeranjangTabel();   // Gambar ulang tabelnya
    }//GEN-LAST:event_TambahPaketButtonActionPerformed

    private void EditPaketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPaketButtonActionPerformed
        // TODO add your handling code here:
        if (indexKeranjangTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data di keranjang yang ingin diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Food selectedFood = (Food) MakananComboBox.getSelectedItem();
        int jumlah = Integer.parseInt(JumlahSpinner.getValue().toString());

        if (selectedFood == null || jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Pilih makanan dan pastikan jumlah lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil objek lama, lalu timpa nilainya
        FoodPackageDetail detailLama = keranjang.get(indexKeranjangTerpilih);
        detailLama.setIdFood(selectedFood.getIdFood());
        detailLama.setNamaFood(selectedFood.getNamaFood());
        detailLama.setJumlah(jumlah);

        refreshKeranjangTabel();
    }//GEN-LAST:event_EditPaketButtonActionPerformed

    private void HapusPaketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPaketButtonActionPerformed
        // TODO add your handling code here:
        if (indexKeranjangTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data di keranjang yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        keranjang.remove(indexKeranjangTerpilih); // Hapus dari memori RAM
        refreshKeranjangTabel();
    }//GEN-LAST:event_HapusPaketButtonActionPerformed

    private void MenuUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtamaButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuAdminFrame().setVisible(true);
    }//GEN-LAST:event_MenuUtamaButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PackageFoodFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DeskripsiTextArea;
    private javax.swing.JButton EditPaketButton;
    private javax.swing.JButton HapusPaketButton;
    private javax.swing.JTextField HargaTextField;
    private javax.swing.JSpinner JumlahSpinner;
    private javax.swing.JTable KeranjangTable;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JComboBox MakananComboBox;
    private javax.swing.JButton MenuUtamaButton;
    private javax.swing.JTextField NamaPaketTextField;
    private javax.swing.JButton SimpanPaketButton;
    private javax.swing.JButton TambahPaketButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
