/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.admin;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import java.util.List;
import bioskop.dao.SeatDAO;
import bioskop.dao.StudioDAO;
import bioskop.model.Seat;
import bioskop.model.Studio;
import bioskop.view.auth.LoginFrame;

public class SeatFrame extends javax.swing.JFrame {
    
    private int idKursiTerpilih = -1;
    private ButtonGroup jenisKursiGroup;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeatFrame.class.getName());

    /**
     * Creates new form KelolaKursi
     */
    public SeatFrame() {
        initComponents();
        setupRadioButton();
        loadComboBoxData();
        loadDataTable();
    }
    
    private void setupRadioButton(){
        jenisKursiGroup = new ButtonGroup();
        jenisKursiGroup.add(RegularRadioButton);
        jenisKursiGroup.add(CoupleRadioButton);
        
        RegularRadioButton.setSelected(true);
    }
    
    private void loadComboBoxData(){
        StudioComboBox.removeAllItems();
        StudioDAO studioDAO = new StudioDAO();
        for (Studio s: studioDAO.getAllStudios()){
            StudioComboBox.addItem(s);
        }
    }
    
    private void loadDataTable(){
        DefaultTableModel model = (DefaultTableModel) KursiTable.getModel();
        model.setRowCount(0);

        SeatDAO dao = new SeatDAO();
        List<Seat> list = dao.getAllSeats();

        // Urutan kolom: ID Kursi, Nama Studio, Nomor Kursi, Jenis Kursi, Status
        for (Seat s : list) {
            model.addRow(new Object[]{
                s.getIdKursi(),
                s.getNamaStudio(),
                s.getNomorKursi(),
                s.getJenisKursi(),
                s.getStatus()
            });
        }
    }
    
    private void clearFields(){
        if (StudioComboBox.getItemCount() > 0) StudioComboBox.setSelectedIndex(0);
        NmrKursiTextField.setText("");
        RegularRadioButton.setSelected(true); // Kembali ke default
        StatusComboBox.setSelectedIndex(0);
        idKursiTerpilih = -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StudioComboBox = new javax.swing.JComboBox();
        NmrKursiTextField = new javax.swing.JTextField();
        RegularRadioButton = new javax.swing.JRadioButton();
        CoupleRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        KursiTable = new javax.swing.JTable();
        TambahButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        MenuUtamaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kelola Kursi");

        jLabel2.setText("Studio");

        jLabel3.setText("Nomor Kursi");

        jLabel4.setText("Jenis Kursi");

        StudioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StudioComboBox.setSelectedIndex(-1);

        RegularRadioButton.setText("Regular");

        CoupleRadioButton.setText("Couple");

        jLabel5.setText("Status");

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Dipesan", "Rusak" }));
        StatusComboBox.setSelectedIndex(-1);

        KursiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Studio", "Nomor Kursi", "Jenis Kursi", "Status"
            }
        ));
        KursiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KursiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(KursiTable);

        TambahButton.setText("Tambah");
        TambahButton.addActionListener(this::TambahButtonActionPerformed);

        EditButton.setText("Edit");
        EditButton.addActionListener(this::EditButtonActionPerformed);

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(this::HapusButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        MenuUtamaButton.setText("Menu Utama");
        MenuUtamaButton.addActionListener(this::MenuUtamaButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StudioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NmrKursiTextField)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(RegularRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CoupleRadioButton))
                                .addComponent(StatusComboBox, 0, 219, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(TambahButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EditButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HapusButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(LogoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuUtamaButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(StudioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NmrKursiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RegularRadioButton)
                            .addComponent(CoupleRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TambahButton)
                            .addComponent(EditButton)
                            .addComponent(HapusButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuUtamaButton)
                            .addComponent(LogoutButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void MenuUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtamaButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuAdminFrame().setVisible(true);
    }//GEN-LAST:event_MenuUtamaButtonActionPerformed

    private void KursiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KursiTableMouseClicked
        // TODO add your handling code here:
        int row = KursiTable.getSelectedRow();
        if (row != -1) {
            idKursiTerpilih = Integer.parseInt(KursiTable.getValueAt(row, 0).toString());
            
            // 1. Set ComboBox Studio
            String namaStudio = KursiTable.getValueAt(row, 1).toString();
            for (int i = 0; i < StudioComboBox.getItemCount(); i++) {
                if (StudioComboBox.getItemAt(i).toString().equals(namaStudio)) {
                    StudioComboBox.setSelectedIndex(i);
                    break;
                }
            }

            // 2. Set TextField Nomor Kursi
            NmrKursiTextField.setText(KursiTable.getValueAt(row, 2).toString());

            // 3. Set RadioButton Jenis Kursi
            String jenis = KursiTable.getValueAt(row, 3).toString();
            if (jenis.equalsIgnoreCase("Couple")) {
                CoupleRadioButton.setSelected(true);
            } else {
                RegularRadioButton.setSelected(true);
            }

            // 4. Set ComboBox Status
            StatusComboBox.setSelectedItem(KursiTable.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_KursiTableMouseClicked

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        Studio selectedStudio = (Studio) StudioComboBox.getSelectedItem();
        String nomorKursi = NmrKursiTextField.getText();
        String status = StatusComboBox.getSelectedItem().toString();
        
        // Cek radio button mana yang dipilih
        String jenisKursi = RegularRadioButton.isSelected() ? "Regular" : "Couple";

        if (selectedStudio == null || nomorKursi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Studio dan Nomor Kursi harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Seat kursi = new Seat(0, selectedStudio.getIdStudio(), nomorKursi, jenisKursi, status);
        SeatDAO dao = new SeatDAO();

        if (dao.insertSeat(kursi)) {
            JOptionPane.showMessageDialog(this, "Kursi baru berhasil ditambahkan!");
            loadDataTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan kursi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        if (idKursiTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kursi dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Studio selectedStudio = (Studio) StudioComboBox.getSelectedItem();
        String nomorKursi = NmrKursiTextField.getText();
        String status = StatusComboBox.getSelectedItem().toString();
        String jenisKursi = RegularRadioButton.isSelected() ? "Regular" : "Couple";

        if (selectedStudio == null || nomorKursi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Studio dan Nomor Kursi harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Seat kursi = new Seat(idKursiTerpilih, selectedStudio.getIdStudio(), nomorKursi, jenisKursi, status);
        SeatDAO dao = new SeatDAO();

        if (dao.updateSeat(kursi)) {
            JOptionPane.showMessageDialog(this, "Data kursi berhasil diperbarui!");
            loadDataTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data kursi.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
        if (idKursiTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kursi dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus kursi ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            SeatDAO dao = new SeatDAO();
            if (dao.deleteSeat(idKursiTerpilih)) {
                JOptionPane.showMessageDialog(this, "Kursi berhasil dihapus!");
                loadDataTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus kursi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SeatFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CoupleRadioButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton HapusButton;
    private javax.swing.JTable KursiTable;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MenuUtamaButton;
    private javax.swing.JTextField NmrKursiTextField;
    private javax.swing.JRadioButton RegularRadioButton;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JComboBox StudioComboBox;
    private javax.swing.JButton TambahButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
