/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.admin;

import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import bioskop.dao.ShowtimeDAO;
import bioskop.dao.FilmDAO;
import bioskop.dao.StudioDAO;
import bioskop.model.Showtime;
import bioskop.model.Film;
import bioskop.model.Studio;
import bioskop.view.auth.LoginFrame;

public class ShowtimeFrame extends javax.swing.JFrame {
    
    private int idJadwalTerpilih = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowtimeFrame.class.getName());
    
    /**
     * Creates new form KelolaJadwalTayang
     */
    public ShowtimeFrame() {
        initComponents();
        loadComboBoxData();
        loadDataTable();

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);

        JamTayangSpinner.setValue(cal.getTime());
    }

    private void loadComboBoxData() {
        FilmComboBox.removeAllItems();
        StudioComboBox.removeAllItems();

        // Load Film
        FilmDAO filmDAO = new FilmDAO();
        for (Film f : filmDAO.getAllFilms()) {
            FilmComboBox.addItem(f); // Memasukkan objek Film utuh
        }

        // Load Studio
        StudioDAO studioDAO = new StudioDAO();
        for (Studio s : studioDAO.getAllStudios()) {
            StudioComboBox.addItem(s); // Memasukkan objek Studio utuh
        }
    }

    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) JadwalTayangTable.getModel();
        model.setRowCount(0);

        ShowtimeDAO dao = new ShowtimeDAO();
        List<Showtime> list = dao.getAllShowtimes();

        // Urutan kolom: ID Jadwal, Judul Film, Nama Studio, Tanggal, Jam, Harga
        for (Showtime s : list) {
            model.addRow(new Object[]{
                s.getIdJadwal(),
                s.getJudulFilm(),
                s.getNamaStudio(),
                s.getTanggalTayang(),
                s.getJamTayang(),
                s.getHargaTiket()
            });
        }
    }

    private void clearFields() {
        if (FilmComboBox.getItemCount() > 0) FilmComboBox.setSelectedIndex(0);
        if (StudioComboBox.getItemCount() > 0) StudioComboBox.setSelectedIndex(0);
        TanggalTayangDateChooser.setDate(null);
        JamTayangSpinner.setValue(new Date()); // Reset ke jam saat ini
        HargaTiketTextField.setText("");
        idJadwalTerpilih = -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TanggalTayangDateChooser = new com.toedter.calendar.JDateChooser();
        JamTayangSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        JadwalTayangTable = new javax.swing.JTable();
        FilmComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StudioComboBox = new javax.swing.JComboBox();
        HargaTiketTextField = new javax.swing.JTextField();
        TambahButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        MenuUtamaButton = new javax.swing.JButton();

        jButton6.setText("jButton6");

        jButton5.setText("Logout");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton4.setText("Menu Utama");

        jButton3.setText("Hapus");

        jButton2.setText("Edit");

        jButton1.setText("Tambah");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kelola Jadwal Tayang Film");

        jLabel2.setText("Tanggal Tayang");

        jLabel3.setText("Jam Tayang");

        jLabel4.setText("Harga Tiket");

        JamTayangSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1685614740000L), null, null, java.util.Calendar.MINUTE));
        JamTayangSpinner.setEditor(new javax.swing.JSpinner.DateEditor(JamTayangSpinner, "HH:mm"));

        JadwalTayangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fillm", "Studio", "Tanggal Tayang", "Jam Tayang", "Harga"
            }
        ));
        JadwalTayangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JadwalTayangTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JadwalTayangTable);

        FilmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FilmComboBox.setSelectedIndex(-1);

        jLabel5.setText("Film");

        jLabel6.setText("Studio");

        StudioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StudioComboBox.setSelectedIndex(-1);

        TambahButton.setText("Tambah");
        TambahButton.addActionListener(this::TambahButtonActionPerformed);

        EditButton.setText("Edit");
        EditButton.addActionListener(this::EditButtonActionPerformed);

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(this::HapusButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        MenuUtamaButton.setText("Menu Utama");
        MenuUtamaButton.addActionListener(this::MenuUtamaButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TambahButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JamTayangSpinner)
                            .addComponent(FilmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TanggalTayangDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StudioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HargaTiketTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(HapusButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(LogoutButton)
                        .addGap(18, 18, 18)
                        .addComponent(MenuUtamaButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(StudioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TanggalTayangDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JamTayangSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(HargaTiketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TambahButton)
                            .addComponent(EditButton)
                            .addComponent(HapusButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LogoutButton)
                            .addComponent(MenuUtamaButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil ID dari objek yang dipilih di ComboBox
            Film selectedFilm = (Film) FilmComboBox.getSelectedItem();
            Studio selectedStudio = (Studio) StudioComboBox.getSelectedItem();
            
            if (selectedFilm == null || selectedStudio == null || TanggalTayangDateChooser.getDate() == null || HargaTiketTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua formulir harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idFilm = selectedFilm.getIdFilm();
            int idStudio = selectedStudio.getIdStudio();
            
            // Konversi java.util.Date ke java.sql.Date dan java.sql.Time
            java.sql.Date sqlDate = new java.sql.Date(TanggalTayangDateChooser.getDate().getTime());
            java.sql.Time sqlTime = new java.sql.Time(((Date) JamTayangSpinner.getValue()).getTime());
            
            double harga = Double.parseDouble(HargaTiketTextField.getText());

            Showtime jadwal = new Showtime(0, idFilm, idStudio, sqlDate, sqlTime, harga);
            ShowtimeDAO dao = new ShowtimeDAO();

            if (dao.insertShowtime(jadwal)) {
                JOptionPane.showMessageDialog(this, "Jadwal tayang berhasil ditambahkan!");
                loadDataTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan jadwal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga tiket harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
                int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void MenuUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtamaButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuAdminFrame().setVisible(true);
    }//GEN-LAST:event_MenuUtamaButtonActionPerformed

    private void JadwalTayangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JadwalTayangTableMouseClicked
        // TODO add your handling code here:
        int row = JadwalTayangTable.getSelectedRow();
        if (row != -1) {
            idJadwalTerpilih = Integer.parseInt(JadwalTayangTable.getValueAt(row, 0).toString());
            
            // 1. Set ComboBox Film
            String judulFilm = JadwalTayangTable.getValueAt(row, 1).toString();
            for (int i = 0; i < FilmComboBox.getItemCount(); i++) {
                if (FilmComboBox.getItemAt(i).toString().equals(judulFilm)) {
                    FilmComboBox.setSelectedIndex(i);
                    break;
                }
            }

            // 2. Set ComboBox Studio
            String namaStudio = JadwalTayangTable.getValueAt(row, 2).toString();
            for (int i = 0; i < StudioComboBox.getItemCount(); i++) {
                if (StudioComboBox.getItemAt(i).toString().equals(namaStudio)) {
                    StudioComboBox.setSelectedIndex(i);
                    break;
                }
            }

            // 3. Set Tanggal
            try {
                Date tanggal = java.sql.Date.valueOf(JadwalTayangTable.getValueAt(row, 3).toString());
                TanggalTayangDateChooser.setDate(tanggal);
            } catch (Exception e) { e.printStackTrace(); }

            // 4. Set Jam
            try {
                SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                Date jam = format.parse(JadwalTayangTable.getValueAt(row, 4).toString());
                JamTayangSpinner.setValue(jam);
            } catch (Exception e) { e.printStackTrace(); }

            // 5. Set Harga
            HargaTiketTextField.setText(JadwalTayangTable.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_JadwalTayangTableMouseClicked

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        if (idJadwalTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih jadwal dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Film selectedFilm = (Film) FilmComboBox.getSelectedItem();
            Studio selectedStudio = (Studio) StudioComboBox.getSelectedItem();
            
            if (selectedFilm == null || selectedStudio == null || TanggalTayangDateChooser.getDate() == null || HargaTiketTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua formulir harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idFilm = selectedFilm.getIdFilm();
            int idStudio = selectedStudio.getIdStudio();
            java.sql.Date sqlDate = new java.sql.Date(TanggalTayangDateChooser.getDate().getTime());
            java.sql.Time sqlTime = new java.sql.Time(((Date) JamTayangSpinner.getValue()).getTime());
            double harga = Double.parseDouble(HargaTiketTextField.getText());

            Showtime jadwal = new Showtime(idJadwalTerpilih, idFilm, idStudio, sqlDate, sqlTime, harga);
            ShowtimeDAO dao = new ShowtimeDAO();

            if (dao.updateShowtime(jadwal)) {
                JOptionPane.showMessageDialog(this, "Jadwal tayang berhasil diperbarui!");
                loadDataTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui jadwal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga tiket harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
        if (idJadwalTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih jadwal dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus jadwal tayang ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            ShowtimeDAO dao = new ShowtimeDAO();
            if (dao.deleteShowtime(idJadwalTerpilih)) {
                JOptionPane.showMessageDialog(this, "Jadwal tayang berhasil dihapus!");
                loadDataTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus jadwal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShowtimeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JComboBox FilmComboBox;
    private javax.swing.JButton HapusButton;
    private javax.swing.JTextField HargaTiketTextField;
    private javax.swing.JTable JadwalTayangTable;
    private javax.swing.JSpinner JamTayangSpinner;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MenuUtamaButton;
    private javax.swing.JComboBox StudioComboBox;
    private javax.swing.JButton TambahButton;
    private com.toedter.calendar.JDateChooser TanggalTayangDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
