/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bioskop.view.admin;

import bioskop.view.auth.LoginFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import bioskop.dao.StudioDAO;
import bioskop.model.Studio;

public class StudioFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudioFrame.class.getName());

    private int idStudioTerpilih = -1;
    
    public StudioFrame() {
        initComponents();
        
        loadDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KapasitasTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NamaStudioTextField = new javax.swing.JTextField();
        JenisStudioComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudioTable = new javax.swing.JTable();
        TambahButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        MenuUtamaButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        KapasitasSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Kelola Studio");

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis");

        jLabel4.setText("Kapasitas");

        JenisStudioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular ", "Velvet ", "Gold" }));
        JenisStudioComboBox.setSelectedIndex(-1);

        StudioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Studio", "Jenis Studio", "Kapasitas"
            }
        ));
        StudioTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudioTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudioTable);

        TambahButton.setText("Tambah");
        TambahButton.addActionListener(this::TambahButtonActionPerformed);

        EditButton.setText("Edit");
        EditButton.addActionListener(this::EditButtonActionPerformed);

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(this::HapusButtonActionPerformed);

        MenuUtamaButton.setText("Menu Utama");
        MenuUtamaButton.addActionListener(this::MenuUtamaButtonActionPerformed);

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(this::LogoutButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TambahButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HapusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(MenuUtamaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NamaStudioTextField)
                            .addComponent(JenisStudioComboBox, 0, 214, Short.MAX_VALUE)
                            .addComponent(KapasitasSpinner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaStudioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JenisStudioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LogoutButton)
                    .addComponent(KapasitasSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TambahButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EditButton)
                        .addComponent(HapusButton)
                        .addComponent(MenuUtamaButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudioTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudioTableMouseClicked
        // TODO add your handling code here:
        int row = StudioTable.getSelectedRow();
        if (row != -1){
            idStudioTerpilih = Integer.parseInt(StudioTable.getValueAt(row, 0).toString());
            NamaStudioTextField.setText(StudioTable.getValueAt(row,1).toString());
            JenisStudioComboBox.setSelectedItem(StudioTable.getValueAt(row,2).toString());
            
            int kapasitas = Integer.parseInt(StudioTable.getValueAt(row, 3).toString());
            KapasitasSpinner.setValue(kapasitas);
        }
    }//GEN-LAST:event_StudioTableMouseClicked

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        String nama = NamaStudioTextField.getText();
        String jenis = JenisStudioComboBox.getSelectedItem().toString();
        int kapasitas = Integer.parseInt(KapasitasSpinner.getValue().toString());
        
        if (nama.isEmpty() || kapasitas <= 0){
            JOptionPane.showMessageDialog(this, "Nama Studio harus diisi dan kapasitas harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        
        Studio studio = new Studio(0, nama, jenis, kapasitas);
        StudioDAO dao = new StudioDAO();
        
        if (dao.insertStudio(studio)) {
            JOptionPane.showMessageDialog(this, "Studio baru berhasil ditambahkan!");
            loadDataTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan studio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        if (idStudioTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih studio dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = NamaStudioTextField.getText();
        String jenis = JenisStudioComboBox.getSelectedItem().toString();
        int kapasitas = Integer.parseInt(KapasitasSpinner.getValue().toString());

        if (nama.isEmpty() || kapasitas <= 0) {
            JOptionPane.showMessageDialog(this, "Nama studio harus diisi dan kapasitas harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Studio studio = new Studio(idStudioTerpilih, nama, jenis, kapasitas);
        StudioDAO dao = new StudioDAO();

        if (dao.updateStudio(studio)) {
            JOptionPane.showMessageDialog(this, "Data studio berhasil diperbarui!");
            loadDataTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data studio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
        if (idStudioTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih studio dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus studio ini? \n(Jadwal tayang yang terkait dengan studio ini juga bisa terhapus)", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            StudioDAO dao = new StudioDAO();
            if (dao.deleteStudio(idStudioTerpilih)) {
                JOptionPane.showMessageDialog(this, "Studio berhasil dihapus!");
                loadDataTable();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus studio.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin log out?", "Konfirmasi Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();

            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void MenuUtamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtamaButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new MenuAdminFrame().setVisible(true);
    }//GEN-LAST:event_MenuUtamaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudioFrame().setVisible(true));
    }
    
    private void loadDataTable(){
        DefaultTableModel model = (DefaultTableModel) StudioTable.getModel();
        model.setRowCount(0); // Kosongkan tabel sebelum diisi ulang

        StudioDAO dao = new StudioDAO();
        List<Studio> listStudio = dao.getAllStudios();

        // Urutan kolom: ID Studio, Nama Studio, Jenis Studio, Kapasitas
        for (Studio s : listStudio) {
            model.addRow(new Object[]{
                s.getIdStudio(),
                s.getNamaStudio(),
                s.getJenisStudio(),
                s.getKapasitas()
            });
        }
    }
    
    private void clearFields(){
        NamaStudioTextField.setText("");
        JenisStudioComboBox.setSelectedIndex(0);
        KapasitasSpinner.setValue(0); // Mengembalikan spinner ke angka 0
        idStudioTerpilih = -1; // Reset ID
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JButton HapusButton;
    private javax.swing.JComboBox<String> JenisStudioComboBox;
    private javax.swing.JSpinner KapasitasSpinner;
    private javax.swing.JTextField KapasitasTextField;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton MenuUtamaButton;
    private javax.swing.JTextField NamaStudioTextField;
    private javax.swing.JTable StudioTable;
    private javax.swing.JButton TambahButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
